import Search from "./src/components/search"; // Importing Search component
import Table from "./src/components/table"; // Importing Table component
import { State } from "./src/state"; // Importing State class

// Get the root element from the DOM where the app will be rendered
const appElement = document.getElementById("app");

// Create a new instance of the State class
const state = new State();

// Define a function to render the application based on the provided state
function render(st) {
  // Update the inner HTML of the root element with the HTML generated by Search and Table components
  appElement.innerHTML = `
  ${Search({ searchValue: st.searchState })}
  ${Table({
    col1: st.data.belts,
    col2: st.data.champions,
    col1Header: "Belt",
    col2Header: "Champion",
  })}
  `;
  // Get the search input element
  const searchInput = document.getElementById("search");
  // Get the length of the search input value
  const searchValueLen = searchInput.value.length;

  // Set focus to the search input
  searchInput.focus();
  // Set the selection range to the end of the search input text
  searchInput.setSelectionRange(searchValueLen, searchValueLen);

  // Add an event listener to the search input for user input
  searchInput.addEventListener("input", (e) => {
    // eslint-disable-next-line no-param-reassign -- It's a class with a setter!
    st.searchState = e.target.value;
    render(st);
  });
}

render(state);
